CRUD for dish
Nazhadna/nc_project pull request #11
Opened 2021-06-24 22:58 UTC by Nazhadna

2021-06-28 20:55 UTC, Ost-max requested changes

2021-06-28 20:55 UTC, Ost-max commented on src/main/java/com/company/nc_project/controllers/DishController.java
> +        return "Dish " + dishRepository.findById(dishId).orElse(null).getName() + " deleted";
Не совсем понимаю сначала удаляем, а потом ищем по id?

а .orElse(null).getName() не даст НПЕ в случае если не найдено? 

А вообще, можно булл возращать, или вообще void и HTTP  статус  200 или 204. для операций тип delete или update, 

Лучше наверное сначала найти, сохранить имя, а потом удалть.

2021-06-28 20:55 UTC, Ost-max commented on src/main/java/com/company/nc_project/model/Dish.java
> +    private String country;
А у нас нет модельки для country?

2021-06-28 20:55 UTC, Ost-max commented on src/main/java/com/company/nc_project/controllers/DishController.java
> +        return dishRepository.findAll();
Можно ещё добавить методы которые вернут список блюд по странам, и список блюд для конкретного клиента, а так же позволят сохранить блюдо для конкретного клиента

2021-06-28 20:55 UTC, Ost-max commented on src/main/java/com/company/nc_project/controllers/DishController.java
> +        return dishRepository.findAll();
А ещё список блюд по продуктам(на вход список продуктов, на выходе список блюд), и может быть по имеющимся у клиента продуктам(на вход ид клиента, на выходе карта (Блюдо - список продуктов для его приготовления), и список продуктов для конкретного блюда (на вход ид блюда - на выходе список продуктов).

Если какая-то из перечисленных задач сложная или долгая(больше парочки методов, и sql запроса), то давай заведём для неё issue и сделаем потом отдельно.

2021-06-29 21:05 UTC, Nazhadna commented on src/main/java/com/company/nc_project/controllers/DishController.java
> +        return "Dish " + dishRepository.findById(dishId).orElse(null).getName() + " deleted";
Да, что-то напутала с последовательностью действий))

Вроде как RestController возвращает 200 по умолчанию.
Или прописать аннотацию @ResponseStatus(HttpStatus.OK) (вроде как OK соответствует статусу 200)?

Если я не возвращаю текст, то мне и имя блюда не нужно, а если нужно, то наверное как-то вот так:

    public ResponseEntity<String> deleteDish(@PathVariable(value = "id") UUID dishId) {
        String dishName = dishRepository.findById(dishId).orElse(new Dish()).getName();
        dishRepository.deleteById(dishId);
        return new ResponseEntity<>("Dish " + dishName + " deleted successfully", HttpStatus.OK);
    }

Как лучше поступить?

2021-07-02 14:58 UTC, Ost-max commented on src/main/java/com/company/nc_project/controllers/DishController.java
> +        return "Dish " + dishRepository.findById(dishId).orElse(null).getName() + " deleted";
проверь плиз, если 200 то никаких дополнительных аннотаций не надо. 

а вернуть void

public void  deleteDish

2021-07-02 15:00 UTC, Ost-max commented on src/main/java/com/company/nc_project/controllers/DishController.java
> +        return "Dish " + dishRepository.findById(dishId).orElse(null).getName() + " deleted";
return new ResponseEntity(HttpStatus.OK)  или так

2021-07-12 12:19 UTC, merged